#!/usr/bin/env python3
"""Build the thesis figure store: Data_Analysis/DA_in_Paper/figures/<group>/.

    python3 make_figs.py                 # every figure
    python3 make_figs.py k_ladder        # only figures whose name contains this
    python3 make_figs.py --list          # corpora, builders, vendored, planned

This is the ONLY place thesis figures are produced. A draft never draws a figure;
it receives a copy with ``export_to_draft.py``.

Groups (the subfolders of ../figures/):
    da         charts computed from evaluation data
    demo       raw demonstrations of behaviour: plans, rollouts, frames
    env        environments and constraint sets: renders, scene panels
    schematic  diagrams of the method

Two kinds of figure are placed into the store here:
    generated  drawn by a builder in builders/ from a corpus in sources.py
    vendored   copied from where it was produced (sources.VENDORED), with provenance
Figures drawn with matplotlib (mpl/) run where matplotlib exists and are saved
straight into the store; they appear in the manifest when their file is present.

Writes ../figures/MANIFEST.md: what each figure is, where it came from, and what is
still planned. Stdlib only -- see svg/fmpcc_svg.py.
"""
import argparse
import datetime
import hashlib
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import builders             # noqa: E402
import sources as S         # noqa: E402

STORE = os.path.normpath(os.path.join(HERE, '..', 'figures'))
GROUPS = ('da', 'demo', 'env', 'schematic')
IMAGE_EXT = ('.svg', '.pdf', '.png', '.jpg', '.jpeg')


def sha12(path):
    with open(path, 'rb') as f:
        return hashlib.sha256(f.read()).hexdigest()[:12]


def store_index():
    """-> {stem: [(group, filename), ...]} over every image in the store."""
    idx = {}
    for g in GROUPS:
        d = os.path.join(STORE, g)
        if not os.path.isdir(d):
            continue
        for fn in sorted(os.listdir(d)):
            stem, ext = os.path.splitext(fn)
            if ext.lower() in IMAGE_EXT:
                idx.setdefault(stem, []).append((g, fn))
    return idx


def write_manifest(built, vendored, skipped):
    idx = store_index()
    L = ['# Figure store manifest — generated by `plotting/make_figs.py`, do not edit', '',
         f'Last built **{datetime.date.today().isoformat()}**. Every thesis figure lives in this '
         'store; drafts receive copies via `plotting/export_to_draft.py`.', '']

    L += ['## Generated', '', '| figure | group | corpus | protocol |', '| :-- | :-- | :-- | :-- |']
    for name, group, prov in built:
        corpus, _, protocol = prov.partition(' | ')
        L.append(f'| `{name}` | {group} | `{corpus}` | {protocol} |')

    L += ['', '## Vendored — copied from where they were produced', '',
          'Each was checked against `/workspaces/aux_repo/` before entering the store.', '',
          '| figure | group | source | provenance |', '| :-- | :-- | :-- | :-- |']
    for name, group, rel, prov in vendored:
        L.append(f'| `{name}` | {group} | `{rel}` | {prov} |')

    known = {n for n, _, _ in built} | {n for n, _, _, _ in vendored}
    other = sorted(n for n in idx if n not in known)
    if other:
        L += ['', '## Other files in the store', '',
              'Present in the store but not produced by this run (e.g. a matplotlib figure from `mpl/`).', '',
              '| figure | location |', '| :-- | :-- |']
        for n in other:
            L.append(f'| `{n}` | ' + ', '.join(f'`{g}/{fn}`' for g, fn in idx[n]) + ' |')

    L += ['', '## Planned — specified in a draft, not yet made', '',
          '| figure | group | asked for in | spec |', '| :-- | :-- | :-- | :-- |']
    for name, (group, where, spec) in S.PLANNED.items():
        L.append(f'| `{name}` | {group} | {where} | {spec} |')

    L += ['', '## Excluded — never use as thesis figures', '', '| file | reason |', '| :-- | :-- |']
    for f, why in S.EXCLUDED.items():
        L.append(f'| `{f}` | {why} |')

    dup = {n: locs for n, locs in idx.items() if len({g for g, _ in locs}) > 1}
    if dup:
        L += ['', '## ⚠️ Name collisions across groups', '',
              'A figure name must be unique across groups, or the export cannot decide. Delete the stale copy.', '']
        for n, locs in dup.items():
            L.append(f'- `{n}`: ' + ', '.join(f'`{g}/{fn}`' for g, fn in locs))

    if skipped:
        L += ['', '## Not built this run', '', '| figure | reason |', '| :-- | :-- |']
        for n, why in skipped:
            L.append(f'| `{n}` | {why} |')

    L += ['', '## Corpora', '', '| key | on disk | grade | protocol |', '| :-- | :-- | :-- | :-- |']
    for k, c in S.CORPORA.items():
        L.append(f'| `{k}` | {"yes" if c.available else "**no**"} | {c.status} | {c.protocol} |')
    L.append('')
    with open(os.path.join(STORE, 'MANIFEST.md'), 'w') as f:
        f.write('\n'.join(L))
    return dup


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('match', nargs='?', help='build only figures whose name contains this')
    ap.add_argument('--list', action='store_true')
    a = ap.parse_args()

    if a.list:
        print('corpora:')
        for k, c in S.CORPORA.items():
            print(f'  {"ok " if c.available else "MISS"}  {k:<22} {c.rel}')
        print('generated:')
        for n, g, _ in builders.ALL:
            print(f'  {g:<9} {n}')
        print('vendored:')
        for n, (g, rel, _) in S.VENDORED.items():
            print(f'  {g:<9} {n}   <- {rel}')
        print('planned:')
        for n, (g, where, _) in S.PLANNED.items():
            print(f'  {g:<9} {n}   ({where})')
        return 0

    for g in GROUPS:
        os.makedirs(os.path.join(STORE, g), exist_ok=True)

    built, vendored, skipped = [], [], []
    for name, (group, rel, prov) in S.VENDORED.items():
        if a.match and a.match not in name:
            continue
        src = os.path.join(S.REPO, rel)
        if not os.path.isfile(src):
            print(f'skip   {name}  (source absent)')
            skipped.append((name, f'vendored source absent: {rel}'))
            continue
        # A figure declared in VENDORED_CROP is a diagnostic dashboard: only the cut
        # made by prep/crop_vendored.py may be used. Copying the source instead would
        # put six panels where the chapter argues from one, so this SKIPS rather than
        # falls back -- a missing figure is visible, a wrong one is not.
        cut = S.prepared_path(name)
        if cut is not None:
            if not os.path.isfile(cut):
                print(f'skip   {name}  (needs prep/crop_vendored.py)')
                skipped.append((name, 'cut declared in VENDORED_CROP but data/prepared/ '
                                      'has no file; run python3.14 plotting/prep/crop_vendored.py'))
                continue
            if os.path.getmtime(src) > os.path.getmtime(cut):
                print(f'skip   {name}  (cut is older than its source)')
                skipped.append((name, 'source is newer than the cut in data/prepared/; '
                                      're-run python3.14 plotting/prep/crop_vendored.py'))
                continue
            entry = S.VENDORED_CROP[name]
            box, keeps, resize = entry[0], entry[1], (entry[2] if len(entry) > 2 else None)
            prov = f'{prov} Cut to {box}: {keeps}.'
            if resize:
                prov = (f'{prov} Stretched to {resize[0]}x{resize[1]} so the plot frame '
                        f'matches the 08-19 panels of the same matrix.')
            src = cut
        dst = os.path.join(STORE, group, name + os.path.splitext(src)[1])
        shutil.copyfile(src, dst)
        print(f'copied {group}/{os.path.basename(dst)}' + ('  (cut)' if cut else ''))
        vendored.append((name, group, rel, prov))

    for name, group, fn in builders.ALL:
        if a.match and a.match not in name:
            continue
        try:
            res = fn(os.path.join(STORE, group))
        except Exception as e:                       # one broken figure must not stop the rest
            print(f'FAIL   {name}: {type(e).__name__}: {e}')
            skipped.append((name, f'builder raised {type(e).__name__}'))
            continue
        if res is None:
            print(f'skip   {name}  (corpus not on this machine)')
            skipped.append((name, 'corpus directory absent'))
            continue
        path, prov = res
        print(f'wrote  {group}/{os.path.basename(path)}')
        built.append((name, group, prov))

    dup = write_manifest(built, vendored, skipped)
    print(f'\n{len(built)} generated + {len(vendored)} vendored figure(s); '
          f'{len(S.PLANNED)} planned. Manifest: figures/MANIFEST.md')
    if dup:
        print(f'WARNING: {len(dup)} name(s) exist in more than one group: {", ".join(dup)}')
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
