"""MJCF generator for the `pillars_v2` scene (Gen15 U18). Pure python: run it anywhere.

    python uav_avoiding_bridge/scene.py            # (re)writes scene_avoiding_pillars_<tag>.xml beside the other scenes
    python uav_avoiding_bridge/scene.py --print    # print the XML

The XML is generated from frame.py so the scene and the transform cannot disagree; plant.py additionally asserts
at load time that every pillar geom sits at to_world_xy(obstacle) (single source of truth = frame.py).
Structure copied from scene_pillars.xml (same drone include, floor, lighting, pillar material).
"""
import os
import sys

from uav_avoiding_bridge import frame as F

_HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(_HERE)
SCENES_DIR = os.path.join(REPO, 'd3il', 'environments', 'd3il', 'models', 'mj', 'robot', 'quadrotor', 'scenes')


def scene_xml_path(scale=None):
    return os.path.join(SCENES_DIR, f'scene_avoiding_pillars_{F.scene_tag(scale)}.xml')


def build_scene_xml(scale=None):
    s = F.SCALE if scale is None else scale
    (x0, x1), (y0, y1) = F.world_field(s)
    fx = F.to_world_xy(0.5, F.GOAL_Y_A, s)[0]
    half_h = F.PILLAR_HEIGHT / 2.0
    floor = max(10.0, abs(x0) + 3, abs(x1) + 3, abs(y0) + 3, abs(y1) + 3)
    pillars = []
    for n, xa, ya, r in F.OBSTACLES_A:
        X, Y = F.to_world_xy(xa, ya, s)
        pillars.append(f'    <geom name="pillar_{n}" type="cylinder" pos="{X:.4f} {Y:.4f} {half_h:.3f}" '
                       f'size="{s * r:.4f} {half_h:.3f}" material="pillar"/>')
    pillars = '\n'.join(pillars)
    return f'''<mujoco model="UAV Avoiding-Pillars Scene (pillars_v2, scale {s:g})">
  <!-- [Gen15 U18 2026-09-22] GENERATED by uav_avoiding_bridge/scene.py from uav_avoiding_bridge/frame.py.
       Do not edit by hand: re-run `python uav_avoiding_bridge/scene.py`.
       The D3IL-avoiding obstacle field (6 cylinders, 3 rows) mapped by a similarity transform:
         X = s*(y_a - {F.ORIGIN_A[1]}),  Y = -s*(x_a - {F.ORIGIN_A[0]}),  s = {s:g}
       Progress along +X: start ({F.to_world_xy(*F.START_A, s)[0]:.2f}, {F.to_world_xy(*F.START_A, s)[1]:.2f}),
       finish line X = {fx:.2f} (avoiding y_a > {F.GOAL_Y_A:.2f}). Pillars {F.PILLAR_HEIGHT:g} m tall = the
       "infinite" extrusion; the drone flies at z = {F.ALTITUDE:g}. The planner's constraints are NOT in this file:
       they stay in the avoiding frame (config/projection_eval.yaml) where projector and scorer read them. -->
  <include file="../quadrotor_modified.xml"/>
  <compiler meshdir="../assets" texturedir="../assets"/>

  <visual>
    <headlight diffuse="0.6 0.6 0.6" ambient="0.3 0.3 0.3" specular="0 0 0"/>
    <rgba haze="0.15 0.25 0.35 1"/>
    <global azimuth="120" elevation="-20"/>
  </visual>

  <asset>
    <texture type="skybox" builtin="gradient" rgb1="0.3 0.5 0.7" rgb2="0 0 0" width="32" height="32"/>
    <texture type="2d" name="groundplane" builtin="checker" mark="edge"
             rgb1="0.2 0.3 0.4" rgb2="0.1 0.2 0.3" markrgb="0.8 0.8 0.8"
             width="300" height="300"/>
    <material name="groundplane" texture="groundplane" texuniform="true" texrepeat="5 5"/>
    <material name="pillar" rgba="0.85 0.55 0.25 1"/>
    <material name="finish" rgba="0 1 0 0.3"/>
  </asset>

  <worldbody>
    <light name="overhead" pos="0 0 8" dir="0 0 -1" diffuse="0.8 0.8 0.8"/>
    <geom name="floor" type="plane" size="{floor:.1f} {floor:.1f} 0.05" material="groundplane"/>

    <!-- 6 pillars = the avoiding obstacles (l1 / l2_top l2_bottom / l3_top l3_mid l3_bottom), scaled x{s:g} -->
{pillars}

    <!-- finish line (visual only, no collision): avoiding y_a = {F.GOAL_Y_A:.2f} -> world X = {fx:.2f} -->
    <geom name="finish_line" type="box" pos="{fx:.4f} 0 0.01" size="0.02 {0.5 * (y1 - y0) + 0.5:.3f} 0.005"
          material="finish" contype="0" conaffinity="0"/>
  </worldbody>
</mujoco>
'''


def write_scene_xml(scale=None):
    path = scene_xml_path(scale)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as fh:
        fh.write(build_scene_xml(scale))
    return path


if __name__ == '__main__':
    if '--print' in sys.argv:
        print(build_scene_xml())
    else:
        print('wrote', write_scene_xml())
        print(F.describe())
